# Generated by Django 2.1.1 on 2018-10-31 00:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('password', models.TextField()),
                ('c_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
